//! Rendering the skip list for other tools.
//!
//! tywb decides what gets *indexed*; a crawler decides what gets *fetched*.
//! They answer the same question about wiki talk pages, session IDs and
//! addresses that were never public, so the answer is written down once — here,
//! in tywb's skip list — and handed to the crawler from this module.
//!
//! The target format is the exclusion file [Zeno] takes via `--exclusion-file`:
//! one Go `regexp` per line, `#` comments, blank lines ignored. That is the
//! same RE2 syntax Rust's `regex` crate accepts, which is why the URL patterns
//! transfer unchanged and only the domains need translating.
//!
//! What is rendered is the list *in force* — the patterns that compiled, not
//! the ones that were asked for. A rejected pattern filters nothing here and
//! must not appear to filter anything there.
//!
//! [Zeno]: https://github.com/internetarchive/Zeno

use warc_search_config::IndexerConfig;

/// Turn a domain skip entry into a Zeno exclusion regex.
///
/// tywb matches a domain and every subdomain of it. The regex says the same: an
/// optional dotted prefix, the domain, then a delimiter or the end of the URL —
/// so `example.com` covers `www.example.com` but neither `notexample.com` nor
/// `example.com.attacker.net`.
pub fn domain_to_regex(domain: &str) -> String {
    let escaped = regex::escape(domain.trim());
    format!(r"(?i)^https?://([^/]*\.)?{escaped}([:/?#]|$)")
}

/// Render the whole skip list as a Zeno exclusion file.
///
/// The URL patterns are emitted with the comments and spacing of the file they
/// were read from — an exclusion file whose rules nobody can explain is one
/// nobody dares to edit. Patterns that failed to compile are dropped from that
/// stream: they are inert in tywb and must be inert in the crawler too.
pub fn to_zeno_exclusions(indexer: &IndexerConfig) -> String {
    let active: std::collections::HashSet<&str> =
        indexer.active_url_patterns().iter().map(String::as_str).collect();

    let mut out = String::new();
    out.push_str(
        "# Zeno exclusion file — generated by tywb, do not edit.\n\
         #\n\
         # Fetch a fresh copy from the tywb server:\n\
         #     curl -o exclusions.txt http://<tywb>/skiplist.zeno\n\
         #\n\
         # These are the rules tywb applies to its index. Crawling what tywb\n\
         # would only throw away costs bandwidth on both ends, so the crawler\n\
         # gets the same list. Edit it in tywb's skip list, not here.\n\
         #\n\
         # One Go regexp per line, matched against the whole URL.\n",
    );

    // Patterns, in the order and shape they were written.
    let source = indexer.url_pattern_source();
    let mut emitted: std::collections::HashSet<&str> = std::collections::HashSet::new();
    if !source.is_empty() {
        out.push_str("\n# ── URL patterns ──────────────────────────────────────────────────\n");
        for line in source {
            if line.is_empty() || line.starts_with('#') {
                out.push_str(line);
                out.push('\n');
            } else if active.contains(line.as_str()) {
                out.push_str(line);
                out.push('\n');
                emitted.insert(line.as_str());
            }
            // A source line that is neither a comment nor active was rejected
            // at startup; it was logged there and is simply absent here.
        }
    }

    // Patterns configured inline in config.yaml have no source line to follow.
    let inline: Vec<&String> = indexer
        .active_url_patterns()
        .iter()
        .filter(|p| !emitted.contains(p.as_str()))
        .collect();
    if !inline.is_empty() {
        out.push_str(
            "\n# ── URL patterns from config.yaml ─────────────────────────────────\n",
        );
        for pattern in inline {
            out.push_str(pattern);
            out.push('\n');
        }
    }

    if !indexer.blacklisted_domains.is_empty() {
        out.push_str(
            "\n# ── Domains ───────────────────────────────────────────────────────\n\
             # Each entry covers the domain and every subdomain of it.\n",
        );
        let mut seen = std::collections::HashSet::new();
        for domain in &indexer.blacklisted_domains {
            let d = domain.trim().trim_start_matches('*').trim_start_matches('.');
            if d.is_empty() || !seen.insert(d.to_ascii_lowercase()) {
                continue;
            }
            out.push_str(&domain_to_regex(d));
            out.push('\n');
        }
    }

    out
}

#[cfg(test)]
mod tests {
    use super::*;

    /// A config carrying `patterns` (as if read from a file) and `domains`.
    fn config(source: &[&str], domains: &[&str]) -> IndexerConfig {
        use std::io::Write as _;
        let dir = std::env::temp_dir();
        let path = dir.join(format!(
            "tywb-zeno-{}-{}.txt",
            std::process::id(),
            source.len() * 31 + domains.len(),
        ));
        let mut f = std::fs::File::create(&path).unwrap();
        // A header, so the stripping is exercised too.
        writeln!(f, "# header explaining the file").unwrap();
        writeln!(f).unwrap();
        for line in source {
            writeln!(f, "{line}").unwrap();
        }
        f.flush().unwrap();

        let mut cfg = IndexerConfig::default();
        cfg.blacklisted_url_patterns_path = Some(path.to_string_lossy().into_owned());
        cfg.blacklisted_domains = domains.iter().map(|d| (*d).to_owned()).collect();
        cfg.load_url_patterns_file().unwrap();
        cfg.compile_url_patterns();
        std::fs::remove_file(&path).ok();
        cfg
    }

    #[test]
    fn domain_regex_covers_subdomains_only() {
        let re = regex::Regex::new(&domain_to_regex("example.com")).unwrap();
        assert!(re.is_match("https://example.com/"));
        assert!(re.is_match("http://www.example.com/page"));
        assert!(re.is_match("https://deep.sub.example.com:8443/x"));
        assert!(re.is_match("https://example.com"));
        // Neither a look-alike nor a suffix trick.
        assert!(!re.is_match("https://notexample.com/"));
        assert!(!re.is_match("https://example.com.attacker.net/"));
    }

    #[test]
    fn export_keeps_comments_and_order() {
        let cfg = config(
            &["# ── wiki ──", r"(?i)[?&]action=edit", "", "# session junk", r"(?i)[?&]sid="],
            &[],
        );
        let out = to_zeno_exclusions(&cfg);
        let body: Vec<&str> = out.lines().skip_while(|l| !l.starts_with("# ── URL")).collect();
        assert_eq!(
            body,
            vec![
                "# ── URL patterns ──────────────────────────────────────────────────",
                "# ── wiki ──",
                r"(?i)[?&]action=edit",
                "",
                "# session junk",
                r"(?i)[?&]sid=",
            ],
        );
        // The file's own header did not come along.
        assert!(!out.contains("header explaining the file"));
    }

    #[test]
    fn export_omits_patterns_that_did_not_compile() {
        let cfg = config(&[r"(?i)/wiki/Diskussion:", "[unclosed", ".*"], &[]);
        let out = to_zeno_exclusions(&cfg);
        assert!(out.contains(r"(?i)/wiki/Diskussion:"));
        assert!(!out.contains("[unclosed"), "a broken pattern must not be exported");
        assert!(!out.contains(".*"), "a catch-all must not be exported");
    }

    #[test]
    fn export_renders_domains_once() {
        let cfg = config(&[], &["instagram.com", "INSTAGRAM.COM", "google.com"]);
        let out = to_zeno_exclusions(&cfg);
        assert_eq!(out.matches("instagram").count(), 1, "{out}");
        assert!(out.contains(r"(?i)^https?://([^/]*\.)?google\.com([:/?#]|$)"));
    }

    #[test]
    fn every_exported_line_is_a_usable_pattern() {
        // The guard that matters: whatever we hand out must compile, and must
        // not match everything. An empty regex would exclude the entire web.
        let cfg = config(&["# c", r"(?i)[?&]action=edit"], &["example.com"]);
        for line in to_zeno_exclusions(&cfg).lines() {
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let re = regex::Regex::new(line).unwrap_or_else(|e| panic!("{line:?}: {e}"));
            assert!(!re.is_match(""), "{line:?} matches every URL");
        }
    }
}
